import AlertNotification from "@/components/Alert";
import { persistor, store } from "@/redux/store";
import "@/styles/globals.css";
import { Box, CssBaseline } from "@mui/material";
import Head from "next/head";
import "react-image-gallery/styles/css/image-gallery.css";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import CircularProgress from "@mui/material/CircularProgress";
import Authentication from "utils";

export default function App({ Component, pageProps }) {
  return (
    <Provider store={store}>
      <PersistGate loading={<CircularProgress />} persistor={persistor}>
        <CssBaseline />
        <AlertNotification />
        <Head>
          <title>Love Latin Woman</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favorite.png" />
        </Head>
        <Authentication>
          <Component {...pageProps} />
        </Authentication>
      </PersistGate>
    </Provider>
  );
}
