import React from 'react';
import Head from "next/head";
import Navbar from "@/components/Admin/Navbar";
import Dashboard from "@/components/Admin/index"

export default function Home() {
  return (
    <>
      <Head>
        <title>Love Latin Woman</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favorite.png" />
      </Head>
      <Navbar />
      <Dashboard />
    </>
  );
}
