import React from 'react';
import Head from "next/head";
import Login from "./login"

export default function Home() {
  return (
    <>
      <Head>
        <title>My Latin Love</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favorite.png" />
      </Head>
      <Login />
    </>
  );
}
